# Generated by Django 2.2.7 on 2019-11-15 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 19, 45, 53, 586555), verbose_name='Date published'),
        ),
    ]
