# Generated by Django 2.2.7 on 2019-11-18 08:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191115_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 13, 58, 42, 970249), verbose_name='Date published'),
        ),
    ]
